const config = {
    USER_SERVICE: process.env.REACT_APP_USER_SERVICE_API_BASE_URL,
    NOTIFICATION_SERVICE: process.env.REACT_APP_NOTIFICATION_SERVICE_API_BASE_URL,
    MAIN_SERVICE: process.env.REACT_APP_MAIN_SERVICE_API_BASE_URL,
    FILE_SERVER: process.env.REACT_APP_FILE_SERVER_API_BASE_URL
};

export default config;